# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'us-east5-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-image', '.']

steps:
# - name: 'gcr.io/cloudsql-docker/gce-proxy:1.19.1'
#   entrypoint: '/cloud_sql_proxy'
#   args:
#     - '-instances=mia-collab-sandbox:us-central1:pjitai-db=tcp:3306'
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/mia-collab-sandbox/my-docker-repo/my-image', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/mia-collab-sandbox/my-docker-repo/my-image']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'pjitai-web-service', '--image', 'us-central1-docker.pkg.dev/mia-collab-sandbox/my-docker-repo/my-image', '--region', 'us-central1']
images:
- us-central1-docker.pkg.dev/mia-collab-sandbox/my-docker-repo/my-image
options:
  logging: CLOUD_LOGGING_ONLY