version: '3.8'
services:
  rl-app:
    container_name: rl_app
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - rl-app
  mysql:
    image: mysql:5.7
    container_name: rl_mysql
    restart: always
    labels:
      org.md2k.cerebralcortex.name: "MySql"
    ports:
      - 3307:3306 # HOST:CONTAINER
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-pass}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-rl_interface}
    networks:
      - db_network
      - web_network

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 